# fly.toml app configuration file generated for vienna-os on 2026-03-21T15:08:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vienna-os'
primary_region = 'iad'

[build]
  dockerfile = "fly.Dockerfile"

[env]
  HOST = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '3100'
  CORS_ORIGIN = 'https://vienna-os.fly.dev,https://vienna-core.vercel.app,https://regulator.ai'

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
